<a href="https://colab.research.google.com/github/dxmolnar/venture_funding_with_deep_learning/blob/main/Colab_venture_funding_with_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy.

To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook.

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [ ]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

---

## Preparing the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [ ]:
# Importing applicants_data.csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [ ]:
# Reading the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv("applicants_data.csv")

# Reviewing the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Reviewing the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [ ]:
# Dropping the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN", "NAME"])

# Reviewing the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [ ]:
# Creating a list of categorical variables
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Displaying the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [ ]:
# Creating a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [ ]:
# Encoding the categorical variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [20]:
# Creating a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns = enc.get_feature_names_out(categorical_variables))

# Reviewing the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [21]:
# Adding the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df.drop(columns = categorical_variables), encoded_df],axis=1)

# Reviewing the DataFrame
encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [25]:
# Defining the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Displaying a sample of y
display(y)

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [26]:
# Defining features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Reviewing the features DataFrame
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [27]:
# Splitting the preprocessed data into a training and testing dataset
# Assigning the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [31]:
# Creating a StandardScaler instance
scaler = StandardScaler()

ting the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fitting the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [32]:
# Defining the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Reviewing the number of features
number_input_features

116

In [45]:
# Defining the number of neurons in the output layer
number_output_neurons = 1

In [46]:
# Defining the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features +1) //2

# Reviewing the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [47]:
# Defining the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 +1) //2

# Reviewing the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [48]:
# Creating the Sequential model instance
nn = Sequential()

In [49]:
# Adding the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [50]:
# Adding the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [51]:
# Adding the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [52]:
# Displaying the Sequential model summary
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

 dense_4 (Dense)             (None, 29)                1711

 dense_5 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [53]:
# Compiling the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [54]:
# Fitting the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.5757 - accuracy: 0.7195
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5540 - accuracy: 0.7281
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7306
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7300
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7341
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7324
Epoch 7/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5442 - accuracy: 0.7338
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7358
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7364
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7349
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7365
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7373
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7371
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7369
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7381
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7381
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7391
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7382
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7383
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7388
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7390
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7392
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7394
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7402
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7395
Epoch 31/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5349 - accuracy: 0.7393
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7393
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7387
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7388
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7409
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7388
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7399
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5335 - accuracy: 0.7397
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7400
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7396
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7403
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7396
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7399
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7413
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7401
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7414
Epoch 50/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5324 - accuracy: 0.7401

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [55]:
# Evaluating the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Displaying the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5544 - accuracy: 0.7296 - 1s/epoch - 5ms/step
Loss: 0.5543976426124573, Accuracy: 0.7295626997947693

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [56]:
# Setting the model's file path
file_path = "AlphabetSoup.h5"

# Exporting your model to a HDF5 file
nn.save(file_path)

# Downloading your model to your computer
files.download(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [57]:
# Defining the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Reviewing the number of features
number_input_features

116

In [59]:
# Defining the number of neurons in the output layer
number_output_neurons_A1 = 1

In [60]:
# Defining the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 50

# Reviewing the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

50

In [63]:
# Defining the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = 60

# Reviewing the number of hidden nodes in the second layer
hidden_nodes_layer2_A1

60

In [64]:
# Defining the number of hidden nodes for the third hidden layer
hidden_nodes_layer3_A1 = 70

# Reviewing the number of hidden nodes in the second layer
hidden_nodes_layer3_A1

70

In [65]:
# Creating the Sequential model instance
nn_A1 = Sequential()

In [66]:

# First hidden layer
nn_A1.add(Dense(units = hidden_nodes_layer1_A1, input_dim = number_input_features, activation = "relu"))

# Output layer
nn_A1.add(Dense(units = number_output_neurons_A1, activation = "linear"))

# Checking the structure of the model
nn_A1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 50)                5850

 dense_7 (Dense)             (None, 1)                 51

=================================================================
Total params: 5,901
Trainable params: 5,901
Non-trainable params: 0
_________________________________________________________________

In [67]:
# Compiling the Sequential model
nn_A1.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [68]:
# Fitting the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 2.5235 - accuracy: 0.6281
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 1.5402 - accuracy: 0.6860
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 1.6489 - accuracy: 0.6808
Epoch 4/50
804/804 [==============================] - 3s 3ms/step - loss: 1.5210 - accuracy: 0.6887
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 1.5621 - accuracy: 0.6797
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 1.6375 - accuracy: 0.6861
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 1.3998 - accuracy: 0.6983
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 1.5090 - accuracy: 0.6893
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 1.7440 - accuracy: 0.6850
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 1.5644 - accuracy: 0.6930
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 1.3863 - accuracy: 0.7009
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 1.4307 - accuracy: 0.6855
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 1.3034 - accuracy: 0.7006
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 1.4962 - accuracy: 0.6882
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 1.6071 - accuracy: 0.6763
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 1.2325 - accuracy: 0.7081
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 1.2237 - accuracy: 0.7052
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1450 - accuracy: 0.7147
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1965 - accuracy: 0.7092
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1367 - accuracy: 0.7102
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 1.2204 - accuracy: 0.6983
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0466 - accuracy: 0.7175
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 1.1659 - accuracy: 0.7108
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 1.2192 - accuracy: 0.7086
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0451 - accuracy: 0.7171
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0376 - accuracy: 0.7193
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 1.0305 - accuracy: 0.7143
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 1.2942 - accuracy: 0.6909
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 1.3416 - accuracy: 0.7027
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0595 - accuracy: 0.7022
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0059 - accuracy: 0.7127
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 1.0146 - accuracy: 0.6955
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1691 - accuracy: 0.6969
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0099 - accuracy: 0.6844
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.8328 - accuracy: 0.7231
Epoch 36/50
804/804 [==============================] - 3s 3ms/step - loss: 0.8332 - accuracy: 0.7248
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8303 - accuracy: 0.7263
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8313 - accuracy: 0.7249
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8939 - accuracy: 0.7137
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8891 - accuracy: 0.7234
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8767 - accuracy: 0.7225
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.9127 - accuracy: 0.7178
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7755 - accuracy: 0.7258
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7292 - accuracy: 0.7276
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7438 - accuracy: 0.7233
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7644 - accuracy: 0.7273
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7536 - accuracy: 0.7275
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7340 - accuracy: 0.7286
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.7168 - accuracy: 0.7324
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7263 - accuracy: 0.7279

#### Alternative Model 2

In [69]:
# Defining the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Reviewing the number of features
number_input_features

116

In [74]:
# Defining the number of neurons in the output layer
number_output_neurons_A2 = 1

In [70]:
# Defining the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 100

# Reviewing the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

100

In [71]:
# Defining the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = 110

# Reviewing the number of hidden nodes in the second layer
hidden_nodes_layer2_A2

110

In [75]:
# Creating the Sequential model instance
nn_A2 = Sequential()

In [76]:
# First hidden layer
nn_A2.add(Dense(units = hidden_nodes_layer1_A2, input_dim = number_input_features, activation = "relu"))

# Output layer
nn_A2.add(Dense(number_output_neurons_A2, activation = "sigmoid"))

# Checking the structure of the model
nn_A2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 100)               11700

 dense_10 (Dense)            (None, 1)                 101

=================================================================
Total params: 11,801
Trainable params: 11,801
Non-trainable params: 0
_________________________________________________________________

In [77]:
# Compiling the model
nn_A2.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [78]:
# Fitting the model
fit_model_A2 = nn_A2.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5847 - accuracy: 0.7191
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5591 - accuracy: 0.7288
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5549 - accuracy: 0.7284
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5537 - accuracy: 0.7317
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7312
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7298
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7311
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7336
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7328
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7316
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7316
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7336
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7331
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7341
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7333
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7332
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7350
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7352
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7346
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7331
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5416 - accuracy: 0.7351
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7343
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7347
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7347
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7350
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7342
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7350
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7332
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7352
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7352
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7361
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7337
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7345
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7357
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7352
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7368
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7360
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7365
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 45/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5383 - accuracy: 0.7373
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7377
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7363
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7366
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7364

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [79]:
print("Original Model Results")

# Evaluating the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)

# Displaying the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.5544 - accuracy: 0.7296 - 537ms/epoch - 2ms/step
Loss: 0.5543976426124573, Accuracy: 0.7295626997947693

In [80]:
print("Alternative Model 1 Results")

# Evaluating the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose = 2)


# Displaying the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.8264 - accuracy: 0.7255 - 792ms/epoch - 3ms/step
Loss: 0.8264274597167969, Accuracy: 0.7254810333251953

In [81]:
print("Alternative Model 2 Results")

# Evaluating the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose = 2)

# Displaying the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5592 - accuracy: 0.7297 - 779ms/epoch - 3ms/step
Loss: 0.559155285358429, Accuracy: 0.72967928647995

### Step 3: Save each of your alternative models as an HDF5 file.

In [82]:
# Setting the file path for the first alternative model
file_path = "AlphabetSoup_A1.h5"

# Exporting your model to a HDF5 file
nn_A1.save(file_path)

# Downloading the model to your computer
files.download(file_path)

In [83]:
# Setting the file path for the second alternative model
file_path = "AlphabetSoup_A2.h5"

# Exporting your model to a HDF5 file
nn_A2.save(file_path)

# Downloading the model to your computer
files.download(file_path)